### ISSUE TITLE
es6 version of the example of scheme in js

### ISSUE THREAD

**Issue by lin7sh** [buzzdecafe/pres#1]
Hi, I like your slides and site very much, here's the 5 lines es6 version of your scheme js:

```
const cons = (x, y) => f => f(x, y)
const head = f => f((x, y) => x)
const tail = f => f((x, y) => y)
const list = (h, ...t) => t.length === 0 ? cons(h, null) : cons(h, list(...t))
//This line is a comment
```

**Comment by buzzdecafe** [comment]
very nice! that presentation is from about 4 years ago, so ES6 was not what it is today. I must say, I prefer this new syntax. Without all the old-fashioned JS cruft, the ideas are clearer to see.

**Comment by lin7sh** [comment]
pure fun!
